### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '\x0a'

### ISSUE THREAD

**Issue by yang1997yi** [dongkwan-kim/SuperGAT#31]
hello，I meet this error：
Traceback (most recent call last):
  File "SuperGAT/main.py", line 471, in <module>
    many_seeds_result = run_with_many_seeds(main_args, num_total_runs, gpu_id=alloc_gpu[0])
  File "SuperGAT/main.py", line 403, in run_with_many_seeds
    ret = run(_args, gpu_id=gpu_id, **kwargs)
  File "SuperGAT/main.py", line 286, in run
    **dataset_kwargs,
  File "/data1/yangyi/SuperGAT/SuperGAT/data.py", line 634, in get_dataset_or_loader
    dataset = dataset_cls(root=root, **kwargs)
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/datasets/planetoid.py", line 33, in __init__
    super(Planetoid, self).__init__(root, transform, pre_transform)
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/data/in_memory_dataset.py", line 53, in __init__
    pre_filter)
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 93, in __init__
    self._process()
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/data/dataset.py", line 166, in _process
    self.process()
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/datasets/planetoid.py", line 58, in process
    data = read_planetoid_data(self.raw_dir, self.name)
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/io/planetoid.py", line 19, in read_planetoid_data
    items = [read_file(folder, prefix, name) for name in names]
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/io/planetoid.py", line 19, in <listcomp>
    items = [read_file(folder, prefix, name) for name in names]
  File "/data1/yangyi/anaconda3/envs/pt1.4/lib/python3.6/site-packages/torch_geometric/io/planetoid.py", line 66, in read_file
    out = pickle.load(f, encoding='latin1')
**_pickle.UnpicklingError: invalid load key, '\x0a'.**
Do you know how to solve it?my python version is 3.6，Thanks a lot。

**Comment by dongkwan-kim** [comment]
Hi, it looks like an error raised from torch_geometric's internal codes.
I have never seen this kind of error, so I am not sure what the cause exactly is.
Instead, I will let you know my system information.
- docker image: `nvidia/cuda:10.0-cudnn7-devel-ubuntu16.04`
- python: `3.7.6`
